adminUser:
  password: vault:jx-aps-consumer-plm4/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-consumer-plm4:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-consumer-plm4:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: PIPELINE_GITHUB_EMAIL
  token: vault:jx-aps-consumer-plm4/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: vault:jx-aps-consumer-plm4/prow:hmacToken
